openapi: "3.0.0"

info:
  title: Hello Connexion
  version: "1.0"
servers:
  - url: http://localhost:5000/

paths:
  /:
    get:
      x-openapi-router-controller: api.root
      operationId: root
      responses:
        "200":
          description: Root route
          content:
            text/plain:
              schema:
                type: string

  /ping/:
    $ref: "./paths/ping.yaml"
